### ISSUE TITLE
Unable to execute it in Xcode 8.3

### ISSUE THREAD

**Issue by asadali737** [avish07/MultipleTimers#2]
Project `MultlipleTimer.xcodeproj `cannot be opened because it is missing its project.pbxproj file.

<img width="532" alt="screenshot 2017-05-11 15 10 02" src="https://cloud.githubusercontent.com/assets/1748831/25944257/18103522-365c-11e7-8fd2-5518f794f611.png">

**Comment by avish07** [comment]
fixed
